version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  news-app:
    build: .
    container_name: news-app-backend
    ports:
      - "7778:7778"
    env_file:
      - .env
    depends_on:
      - mongodb
    restart: always

volumes:
  mongo-data:
